### ISSUE TITLE
Create the project layout

### ISSUE THREAD

**Issue by ani-sha** [graphqlcrud/graphqlcrud-java#3]

**Comment by wtrocki** [comment]
@ani-sha Lets chat what we need. I can help you with setting up github actions CI/CD. 
We are probably looking into a simple quarkus starter project?

**Comment by ani-sha** [comment]
@wtrocki yes. @rareddy what do you suggest?

**Comment by wtrocki** [comment]
https://code.quarkus.io/ can be used

**Comment by wtrocki** [comment]
Let me know if you need any info what libraries should be put. Idealy the more vanilla experience then better we will add builds and style checkers. Target here is to put tons of infrastructure files to not obfuscate actual prototype we going to write.

**Comment by wtrocki** [comment]
Great work!
