### ISSUE TITLE
Update jooq version to latest  once released

### ISSUE THREAD

**Issue by machi1990** [graphqlcrud/graphqlcrud-java#30]
Currently we are using snapshot release of the jooq library https://github.com/graphqlcrud/graphqlcrud-java/blob/fa8438ed900df91a08d39386b80fc4d3e01e97e8/pom.xml#L43

In the long run and to re-enable CI again and easy local testing, we should replace this with the latest stable jooq. 

/cc @ani-sha @rareddy

**Comment by ani-sha** [comment]
As we are using `jsonbArrayAgg`, it is not available for the latest stable version of JOOQ.

https://github.com/graphqlcrud/graphqlcrud-java/blob/fa8438ed900df91a08d39386b80fc4d3e01e97e8/engine/src/main/java/io/graphqlcrud/SQLQueryBuilderVisitor.java#L166

For reference  [see.](https://www.jooq.org/api-diff/3.13-3.14)

**Comment by machi1990** [comment]
> As we are using `jsonbArrayAgg`, it is not available for the latest stable version of JOOQ.
> 
> https://github.com/graphqlcrud/graphqlcrud-java/blob/fa8438ed900df91a08d39386b80fc4d3e01e97e8/engine/src/main/java/io/graphqlcrud/SQLQueryBuilderVisitor.java#L166
> 

Yes, I noticed that hence the "to latest once released" ;-). I suppose this feature (or its counterpart) is not available in 3.13?


> For reference [see.](https://www.jooq.org/api-diff/3.13-3.14)

Thank's for the link. Do we know when 314 will be released?

**Comment by ani-sha** [comment]
Yes you are right @machi1990 
Not sure about the exact date of release. :/

**Comment by machi1990** [comment]
> Yes you are right @machi1990
> Not sure about the exact date of release. :/

Okay. A line or two in the [build-the-application section of the README](https://github.com/graphqlcrud/graphqlcrud-java/tree/fa8438ed900df91a08d39386b80fc4d3e01e97e8#build-the-application) about how to build [JOOQ](https://github.com/jOOQ/jOOQ) as a pre-requisite can help others when setting up the project locally. It may not be so trivial for others.

**Comment by wtrocki** [comment]
I would add script and extecude it in CI/CD.
Failing build prevents us from tracking some other issues.

**Comment by machi1990** [comment]
> I would add script and extecude it in CI/CD.
> Failing build prevents us from tracking some other issues.

+100. This is a good idea for CI.

```bash
git clone https://github.com/jOOQ/jOOQ
cd jOOQ && mvn clean install -DskipTests -DskipITs
```

I think the above script would do it.

**Comment by rareddy** [comment]
@machi1990 go ahead and submit a patch for this
