### ISSUE TITLE
Generate GraphQL Schema

### ISSUE THREAD

**Issue by ani-sha** [graphqlcrud/graphqlcrud-java#9]

**Comment by wtrocki** [comment]
I will start with generation of single database type.
Let's build some example type like Note

```graphql 
type Note {
 id:ID
 text: String
}
```

**Comment by ani-sha** [comment]
@wtrocki The schema which will be generated will it be written down in any file?

**Comment by wtrocki** [comment]
It need to exist for the moment. Writing to file is not essential. Idea is that this schema can be used to execute queries at runtime. 

We can take two approaches here:

1) codegen - we take database as input and generate schema file and mappings
2) Runtime - we read database mapping file and build schema on startup

I think it makes sense to go with 2 first.
Do you have example of input - what will be used to build schema?

**Comment by ani-sha** [comment]
For now, I am connecting to Teiid and taking the tables as input to build the schema. I have hardcoded the jdbc-url for that.  Later on, it can be for any data source.

**Comment by wtrocki** [comment]
So let's do that first as PR - connect to database and get table data. then we can use `snapshot testing` to see the table structure and talk how to build GraphQL from it
